import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Time Converter to Discord Unix Timestamp
        </h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.yonchukku.dev/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Built By ‎<b> Yonchukku{' '}</b>
          <span className={styles.logo}>
            <Image src="https://www.yonchukku.dev/_next/image?url=%2FFlower.png&w=64&q=64" alt="Vercel Logo" width={16} height={16} />
          </span>
        </a>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
